src/java/com/jxpens/id11965252/controller/PenController.java
package com.jxpens.id11965252.controller;

import com.jxpens.id11965252.dbhelper.PenDAO;
import com.jxpens.id11965252.exception.DataStoreException;
import com.jxpens.id11965252.model.Pen;
import java.io.Serializable;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 * A backing bean for the pen list JSF view
 *
 * @author Shaoxi He 11965252
 */
@Named
@RequestScoped
public class PenController implements Serializable {

    private Pen pen = new Pen();

    /**
     * the current pen object/model that this controller will manipulate
     * @return
     */
    public Pen getPen() {
        return pen;
    }

    /**
     * Save the current pen as a new record in the database.
     * @return a redirect to view the whole pen list
     * @throws com.jxpens.id11965252.exception.DataStoreException
     */
    public String saveNewPen() throws DataStoreException {
        new PenDAO().createPen(pen);
        return "penlist?faces-redirect=true";
    }

    /**
     * Update the record in the database whose database id matches that of the current pen.
     * @return a redirect to view the whole pen list
     * @throws com.jxpens.id11965252.exception.DataStoreException
     */
    public String updatePen() throws DataStoreException {
        new PenDAO().updatePen(pen);
        return "penlist?faces-redirect=true";
    }

    /**
     * Delete the record from the database that matches the current pen's database id.
     * @return a redirect to view the whole pen list
     * @throws com.jxpens.id11965252.exception.DataStoreException
     */
    public String delete() throws DataStoreException {
        new PenDAO().deletePen(pen);
        return "penlist?faces-redirect=true";
    }

    /**
     * Load the details of a pen from the database.
     * @param index the unique database id of the pen to retrieve
     * @throws com.jxpens.id11965252.exception.DataStoreException
     */
    public void loadPen(int index) throws DataStoreException  {
        this.pen = new PenDAO().findPen(index);
    }

    /**
     * Returns a collection containing the entire pen list database.
     * @return 
     * @throws com.jxpens.id11965252.exception.DataStoreException 
     */
    public ArrayList<Pen> getAllPens() throws DataStoreException {
        return new PenDAO().findAll();
    }
}

web/app/createpen.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Create a Pen</title>
        <h:outputStylesheet library="css" name="bootstrap.min.css"/>
        <h:outputStylesheet library="css" name="createpen.css"/>
        <h:outputScript library="js" name="bootstrap.min.js" />
        <h:outputScript library="js" name="jquery.min.js" />
    </h:head>
    <h:body>
        <ui:include src="/nav-header.xhtml"/>
        
        <h:panelGroup layout="block" class="container">
            <h:form class="form-createpen">
                <h1 class="form-create-heading">Create a Pen</h1>
                <div class="form-group">
                    <label for="name">
                        Pen Name:
                    </label>
                    <h:inputText id="name" 
                                 value="#{penController.pen.name}" 
                                 validatorMessage="Please enter a valid name." 
                                 converterMessage="Please enter a valid name." 
                                 required="true" 
                                 requiredMessage="Please enter a name."
                                 class="form-control"/>
                    <h:message for="name" class="error"/>
                </div>
                <div class="form-group">
                    <label for="brand">
                        Brand: 
                    </label>
                    <h:inputText id="brand" 
                                 value="#{penController.pen.brand}" 
                                 validatorMessage="Please enter a valid brand." 
                                 converterMessage="Please enter a valid brand." 
                                 required="true" 
                                 requiredMessage="Please enter a brand."
                                 class="form-control"/>
                    <h:message for="brand" class="error"/>
                </div>
                <div class="form-group">
                    <label for="nibsize">
                        Nib Size:
                    </label>
                    <h:inputText id="nibsize" value="#{penController.pen.nibSize}" 
                                 validatorMessage="Please enter a nib size between 0.3 and 2.5" 
                                 converterMessage="Please enter a size." 
                                 required="true" 
                                 requiredMessage="Please enter a size."
                                 class="form-control"
                                 a:placeholder="between 0.3 and 2.5">
                        <f:validateDoubleRange minimum="0.3" maximum="2.5" />                       
                    </h:inputText>
                    <h:message for="nibsize" class="error"/>
                </div>
                <div class="form-group">
                    <label for="colour">
                        Colour:
                    </label>
                    <h:inputText id="colour" 
                                 value="#{penController.pen.colour}" 
                                 validatorMessage="Please enter a valid colour." 
                                 converterMessage="Please enter a valid colour." 
                                 required="true" 
                                 requiredMessage="Please enter a colour."
                                 class="form-control" />
                    <h:message for="colour"  class="error"/>
                </div>
                <h:commandButton value="Create" action="#{penController.saveNewPen}" class="btn btn-primary"/>
                <h:link value="Cancel" outcome="/app/penlist" class="btn btn-default"/>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

web/app/deletepen.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <f:metadata>
        <f:viewAction action="#{penController.loadPen(param.index)}" />
    </f:metadata>
    <h:head>
        <title>Delete Pen</title>
        <h:outputStylesheet library="css" name="bootstrap.min.css"/>
        <h:outputStylesheet library="css" name="createpen.css"/>
        <h:outputScript library="js" name="bootstrap.min.js" />
        <h:outputScript library="js" name="jquery.min.js" />
    </h:head>
    <h:body>
        <ui:include src="/nav-header.xhtml" />
        <h:panelGroup layout="block" class="container">
            <h:form class="form-createpen">
                <h1>Are you sure to delete this pen?</h1>
                <div class="form-group">
                    <label for="name">
                        Pen Name:
                    </label>
                    <div class="well">
                        <h:outputText value="#{penController.pen.name}" class="form-control-static"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="brand">
                        Brand: 
                    </label>
                    <div class="well">
                        <h:outputText value="#{penController.pen.brand}" class="form-control-static"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="nibsize">
                        Nib Size:
                    </label>
                    <div class="well">
                        <h:outputText value="#{penController.pen.nibSize}" class="form-control-static"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="colour">
                        Colour:
                    </label>
                    <div class="well">
                        <h:outputText value="#{penController.pen.colour}" class="form-control-static"/>
                    </div>
                </div>
                <h:inputHidden value="#{penController.pen.id}"/>
                <h:commandButton value="Delete" action="#{penController.delete}" class="btn btn-danger"/>
                <h:link value="Cancel" outcome="/app/penlist" class="btn btn-default"/>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

web/app/editpen.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough">
    <f:metadata>
        <f:viewAction action="#{penController.loadPen(param.index)}"/>
    </f:metadata>
    <h:head>
        <title>Edit Pen</title>
        <h:outputStylesheet library="css" name="bootstrap.min.css"/>
        <h:outputStylesheet library="css" name="createpen.css"/>
        <h:outputScript library="js" name="bootstrap.min.js" />
        <h:outputScript library="js" name="jquery.min.js" />
    </h:head>
    <h:body>
        <ui:include src="/nav-header.xhtml" />
        <h:panelGroup layout="block" class="container">
            <h:form class="form-createpen">
                <h1 class="form-create-heading">Edit Pen</h1>
                <div class="form-group">
                    <label for="name">
                        Pen Name:
                    </label>
                    <h:inputText id="name" 
                                 value="#{penController.pen.name}" 
                                 validatorMessage="Please enter a valid name." 
                                 converterMessage="Please enter a valid name." 
                                 required="true" 
                                 requiredMessage="Please enter a name."
                                 class="form-control"/>
                    <h:message for="name" class="error"/>
                </div>
                <div class="form-group">
                    <label for="brand">
                        Brand: 
                    </label>
                    <h:inputText id="brand" 
                                 value="#{penController.pen.brand}" 
                                 validatorMessage="Please enter a valid brand." 
                                 converterMessage="Please enter a valid brand." 
                                 required="true" 
                                 requiredMessage="Please enter a brand."
                                 class="form-control"/>
                    <h:message for="brand" class="error"/>
                </div>
                <div class="form-group">
                    <label for="nibsize">
                        Nib Size:
                    </label>
                    <h:inputText id="nibsize" value="#{penController.pen.nibSize}" 
                                 validatorMessage="Please enter a nib size between 0.3 and 2.5" 
                                 converterMessage="Please enter a valid size." 
                                 required="true" 
                                 requiredMessage="Please enter a size."
                                 class="form-control"
                                 a:placeholder="between 0.3 and 2.5">
                        <f:validateDoubleRange minimum="0.3" maximum="2.5" />                       
                    </h:inputText>
                    <h:message for="nibsize" class="error"/>
                </div>
                <div class="form-group">
                    <label for="colour">
                        Colour:
                    </label>
                    <h:inputText id="colour" 
                                 value="#{penController.pen.colour}" 
                                 validatorMessage="Please enter a valid colour." 
                                 converterMessage="Please enter a valid colour." 
                                 required="true" 
                                 requiredMessage="Please enter a colour."
                                 class="form-control" />
                    <h:message for="colour" class="error"/>
                </div>
                <h:inputHidden value="#{penController.pen.id}"/>
                <h:commandButton value="Save Changes" action="#{penController.updatePen}" class="btn btn-primary"/>
                <h:link value="Cancel" outcome="/app/penlist" class="btn btn-default"/>
            </h:form>
        </h:panelGroup>
    </h:body>

</html>

web/app/penlist.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Pen List</title>
        <h:outputStylesheet library="css" name="penlist.css"/>
        <h:outputStylesheet library="css" name="bootstrap.min.css"/>
        <h:outputScript library="js" name="bootstrap.min.js" />
        <h:outputScript library="js" name="jquery.min.js" />
    </h:head>
    <h:body>
        <ui:include src="../nav-header.xhtml"/>
        <h:panelGroup layout="block" class="container">
            <h:dataTable var="pen" id="penlist-table" value="#{penController.allPens}" styleClass="table table-hover">
                <h:column>
                    <f:facet name="header">
                        Name
                    </f:facet>
                    <h:outputText value="#{pen.name}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Brand
                    </f:facet>
                    <h:outputText value="#{pen.brand}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Nib Size
                    </f:facet>
                    <h:outputText value="#{pen.nibSize}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Colour
                    </f:facet>
                    <h:outputText value="#{pen.colour}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Edit
                    </f:facet>
                    <h:link value="Edit" outcome="editpen">
                        <f:param name="index" value="#{pen.id}" />
                    </h:link>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        Delete
                    </f:facet>
                    <h:link value="Delete" outcome="deletepen">
                        <f:param name="index" value="#{pen.id}" />
                    </h:link>
                </h:column>
            </h:dataTable>
        </h:panelGroup>
    </h:body>
</html>