src/java/com/jxpens/id11965252/controller/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jxpens.id11965252.controller;

import com.jxpens.id11965252.model.Account;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

/**
 * A Backing bean handles user Login and Logout
 * 
 * @author harold
 */
@Named
@RequestScoped
public class LoginController {

    private Account account = new Account();

    /**
     * the current user that is logged in
     *
     * @return
     */
    public Account getAccount() {
        return account;
    }

    /**
     * Attempt to log in using the username/password properties set by JSF. Uses
     * the container-managed authentication to perform the password check.
     *
     * @return an outcome corresponding to a secure welcome page, null if the
     * login failed
     */
    public String login() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();

        try {
            request.login(this.account.getUsername(), this.account.getPassword());
            return "/app/penlist?faces-redirect=true";

        } catch (ServletException e) {
            showError("Incorrect username or password.");
            e.printStackTrace();
            return null;
        }
    }

    /**
     * Logs out the current user of the container-managed authentication.
     *
     * @return an outcome corresponding to the login page
     * @throws ServletException if there is no currently logged in user
     */
    public String logout() throws ServletException {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        request.logout();
        return "/login?faces-redirect=true";
    }

    /**
     * Retrieves the username logged in the Server, returns null if no user
     * is logged in
     * @return the username logged in the server
     */
    public String getLoggedUser() {
        FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
        return request.getRemoteUser();
    }

    /**
     * Adds a message to the current faces context, so that it will appear in a
     * h:messages element.
     *
     * @param message the text of the error message to show the user
     */
    private void showError(String message) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage("form-login:loginfail", new FacesMessage(message));
    }

}

web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Login - JXPens</title>
        <h:outputStylesheet library="css" name="bootstrap.min.css"/>
        <h:outputStylesheet library="css" name="login.css"/>
        <h:outputScript library="js" name="bootstrap.min.js" />
        <h:outputScript library="js" name="jquery.min.js" />
    </h:head>
    <h:body>

        <ui:include src="nav-header.xhtml"/>

        <h:panelGroup layout="block" class="container" rendered="#{empty loginController.loggedUser}">
            <h:form class="form-signin" id="form-login">
                <h2 class="form-signin-heading">Login</h2>
                <h:outputLabel value="Username: " class="sr-only" for="username"/>
                <h:inputText id="username" 
                             value="#{loginController.account.username}" 
                             requiredMessage="Please enter a username" 
                             required="true" 
                             validatorMessage="Please enter a valid username"
                             class="form-control"
                             a:placeholder="Username"/>
                
                <h:message for="username" class="error"/>
                
                <h:outputLabel value="Password: " class="sr-only" for="password"/>
                <h:inputSecret id="password"
                               value="#{loginController.account.password}" 
                               required="true" 
                               requiredMessage="Please enter a password"  
                               validatorMessage="Please enter a valid password"
                               class="form-control"
                               a:placeholder="Password"/>
                <h:message for="password" class="error"/>
                <h:message id="loginfail" for="loginfail" class="error"/>
                
                <h:commandButton value="Log in" action="#{loginController.login}"
                                 class="btn btn-lg btn-primary btn-block"/>
                <h:link outcome="register.xhtml" class="btn btn-lg" value="I don't have an account."/>
            </h:form>
        </h:panelGroup>

        <h:panelGroup layout="block" class="container" rendered="#{not empty loginController.loggedUser}">
            <h:form class="form-signin">
                <h2 class="form-signin-heading">Hello, </h2>
                <p>
                    <h:outputText value="You are currently logged as #{loginController.loggedUser}."/>
                </p>
                <p>
                    You can:
                </p>
                <ul>
                    <li>
                        <h:link value="Go to pen list page" class="btn" outcome="app/penlist.xhtml"/>
                    </li>
                </ul>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

web/nav-header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:outputScript library="js" name="bootstrap.min.js"/>
    <h:outputScript library="js" name="jquery.min.js"/>
    
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar" aria-expanded="false"
                        aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span> 
                    <span class="icon-bar"></span> 
                    <span class="icon-bar"></span> 
                    <span class="icon-bar"></span>
                </button>
                <h:link class="navbar-brand" value="JXPens" outcome="/app/penlist"/>
            </div>

            <div id="navbar" class="collapse navbar-collapse">
                <h:outputText class="navbar-text" 
                              value="Welcome, #{loginController.loggedUser}!"
                              rendered="#{not empty loginController.loggedUser}"/>
                <h:form class="navbar-form navbar-left">
                    <h:commandButton class="btn" 
                                     value="Logout" 
                                     action="#{loginController.logout}"
                                     rendered="#{not empty loginController.loggedUser}"/>
                </h:form>
                <h:link value="Create a Pen" 
                        class="btn navbar-btn navbar-right btn-primary"
                        outcome="/app/createpen"
                        rendered="#{not empty loginController.loggedUser}"/>
            </div>
        </div>
    </nav>

</ui:composition>

web/register.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Register</title>
        <h:outputStylesheet library="css" name="bootstrap.min.css"/>
        <h:outputStylesheet library="css" name="login.css"/>
        <h:outputScript library="js" name="bootstrap.min.js" />
        <h:outputScript library="js" name="jquery.min.js" />
    </h:head>
    <h:body>

        <ui:include src="nav-header.xhtml"/>

        <h:panelGroup layout="block" class="container" rendered="#{empty username}">
            <h:form class="form-signin" id="form-rego">
                <h2 class="form-signin-heading">Register</h2>
                <h:outputLabel value="Username: " class="sr-only" for="username"/>
                <h:inputText id="username" 
                             value="#{accountController.account.username}" 
                             requiredMessage="Please enter a username" 
                             required="true" 
                             validatorMessage="Please enter a valid username"
                             class="form-control"
                             a:placeholder="Username"/>
                <h:message for="username" class="error"/>

                <h:outputLabel value="Password: " class="sr-only" for="password"/>
                <h:inputSecret id="password"
                               value="#{accountController.account.password}" 
                               required="true" 
                               requiredMessage="Please enter a password"  
                               converterMessage="Please enter a valid password"
                               validatorMessage="Please enter a valid password"
                               class="form-control"
                               a:placeholder="Password"/>
                <h:message for="password" class="error"/>
                <h:message for="regofail" id="regofail" class="error"/>

                <h:commandButton value="Register" class="btn btn-lg btn-primary btn-block" action="#{accountController.registerNewAccount}"/>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

web/rego-success.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Success! Registration</title>
        <h:outputStylesheet library="css" name="bootstrap.min.css"/>
        <h:outputStylesheet library="css" name="login.css"/>
        <h:outputScript library="js" name="bootstrap.min.js" />
        <h:outputScript library="js" name="jquery.min.js" />
    </h:head>
    <h:body>
        <ui:include src="nav-header.xhtml"/>
        <h:panelGroup layout="block" class="container">
            <h:form class="form-signin">
                <h2 class="form-signin-heading">Congratulations!</h2>
                <p>
                    You have successfully register an account!
                </p>
                <p>
                    You can:
                </p>
                <ul>
                    <li>
                        <h:link value="Go to login page" class="btn" outcome="login.xhtml"/>
                    </li>
                </ul>
            </h:form>
        </h:panelGroup>
    </h:body>
</html>

web/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Welcome to JXPens!</title>
    </h:head>
    <h:body>
  
        <p>
            Welcome to JXPens, <h:outputText value="#{loginController.loggedUser}"/>
        </p>
    </h:body>
</html>